version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      - run: make test
      - run: make

  build-release:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      - run: VERSION="${CIRCLE_TAG}" make dist
      - save_cache:
          key: dist-{{ .Revision }}
          paths:
            - dist/

  upload-release:
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - dist-{{ .Revision }}
      - run: |
          go get -u github.com/tombell/releasekit/cmd/releasekit
          go get -u github.com/tombell/brewer/cmd/brewer
      - run: |
          releasekit -t ${GITHUB_TOKEN} \
                     -o tombell \
                     -r moniker \
                     -p $(git tag | sort -V | tail -2 | head -1) \
                     -n ${CIRCLE_TAG} \
                     --attachment dist/moniker-linux-amd64 \
                     --attachment dist/moniker-darwin-amd64 \
                     --attachment dist/moniker-windows-amd64
      - run: |
          brewer --token ${GITHUB_TOKEN} \
                 --owner tombell \
                 --name homebrew-formulae \
                 --formula Formula/moniker.rb \
                 --tag ${CIRCLE_TAG} \
                 --revision ${CIRCLE_SHA1} \
                 --commit-message "Update Formula/moniker.rb to ${CIRCLE_TAG}" \
                 --commit-author "Tom Bell" \
                 --commit-email "tomb@tomb.io"

workflows:
  version: 2
  build-n-upload:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - build-release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - upload-release:
          requires:
            - build-release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
